CREATE TABLE IF NOT EXISTS operation_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NULL,
  actor_scope VARCHAR(16) NOT NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  operation_type VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payload_fingerprint BINARY(32) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'PROCESSING',
  resource_type VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
  resource_id BIGINT UNSIGNED NULL,
  http_status SMALLINT UNSIGNED NULL,
  response_snapshot JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  completed_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_operation_requests_actor_request (actor_scope, actor_id, operation_type, request_id),
  KEY ix_operation_requests_tenant_created (tenant_id, created_at),
  KEY ix_operation_requests_processing (status, created_at),
  CONSTRAINT fk_operation_requests_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT,
  CONSTRAINT chk_operation_requests_actor_scope CHECK (actor_scope IN ('USER', 'ADMIN', 'JOB')),
  CONSTRAINT chk_operation_requests_status CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS draws (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id BIGINT UNSIGNED NOT NULL,
  draw_schedule_id BIGINT UNSIGNED NOT NULL,
  business_date DATE NOT NULL,
  scheduled_at_utc DATETIME(6) NOT NULL,
  closes_at_utc DATETIME(6) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  lottery_code_snapshot VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  lottery_name_snapshot VARCHAR(100) NOT NULL,
  modality_code_snapshot VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  modality_name_snapshot VARCHAR(100) NOT NULL,
  local_time_snapshot TIME NOT NULL,
  close_minutes_before_snapshot SMALLINT UNSIGNED NOT NULL DEFAULT 10,
  multiplier_snapshot DECIMAL(12,2) NOT NULL,
  general_limit_snapshot DECIMAL(15,2) NOT NULL,
  total_sold_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  valid_ticket_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  current_result_version_id BIGINT UNSIGNED NULL,
  closed_at DATETIME(6) NULL,
  settled_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_draws_public_id (public_id),
  UNIQUE KEY uq_draws_tenant_schedule_date (tenant_id, draw_schedule_id, business_date),
  KEY ix_draws_tenant_date_status (tenant_id, business_date, status),
  KEY ix_draws_tenant_scheduled (tenant_id, scheduled_at_utc),
  KEY ix_draws_status_scheduled (status, scheduled_at_utc),
  KEY ix_draws_status_closes (status, closes_at_utc),
  CONSTRAINT fk_draws_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT,
  CONSTRAINT fk_draws_schedule FOREIGN KEY (draw_schedule_id) REFERENCES draw_schedules (id) ON DELETE RESTRICT,
  CONSTRAINT chk_draws_status CHECK (status IN ('PENDING', 'OPEN', 'CLOSED', 'RESULTED', 'SETTLED', 'CANCELLED')),
  CONSTRAINT chk_draws_times CHECK (closes_at_utc < scheduled_at_utc),
  CONSTRAINT chk_draws_close_minutes CHECK (close_minutes_before_snapshot BETWEEN 10 AND 20),
  CONSTRAINT chk_draws_multiplier CHECK (multiplier_snapshot > 0),
  CONSTRAINT chk_draws_general_limit CHECK (general_limit_snapshot >= 0),
  CONSTRAINT chk_draws_total_sold CHECK (total_sold_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS draw_number_positions (
  draw_id BIGINT UNSIGNED NOT NULL,
  number_value TINYINT UNSIGNED NOT NULL,
  base_limit_amount DECIMAL(15,2) NOT NULL,
  limit_adjustment_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  effective_limit_amount DECIMAL(15,2) NOT NULL,
  sold_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  valid_ticket_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (draw_id, number_value),
  CONSTRAINT fk_draw_number_positions_draw FOREIGN KEY (draw_id) REFERENCES draws (id) ON DELETE RESTRICT,
  CONSTRAINT chk_draw_number_positions_number CHECK (number_value BETWEEN 0 AND 99),
  CONSTRAINT chk_draw_number_positions_base CHECK (base_limit_amount >= 0),
  CONSTRAINT chk_draw_number_positions_effective CHECK (effective_limit_amount >= 0),
  CONSTRAINT chk_draw_number_positions_sold CHECK (sold_amount >= 0 AND sold_amount <= effective_limit_amount),
  CONSTRAINT chk_draw_number_positions_calculation CHECK (effective_limit_amount = base_limit_amount + limit_adjustment_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS cash_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  current_balance DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  initialized_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_cash_accounts_tenant (tenant_id),
  CONSTRAINT fk_cash_accounts_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS cash_movements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  cash_account_id BIGINT UNSIGNED NOT NULL,
  business_date DATE NOT NULL,
  movement_type VARCHAR(32) NOT NULL,
  direction VARCHAR(8) NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  balance_after DECIMAL(15,2) NOT NULL,
  reference_type VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reference_id BIGINT UNSIGNED NOT NULL,
  operation_request_id BIGINT UNSIGNED NULL,
  reason VARCHAR(500) NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_cash_movements_reference (tenant_id, movement_type, reference_type, reference_id),
  KEY ix_cash_movements_operation_request (operation_request_id),
  KEY ix_cash_movements_tenant_date (tenant_id, business_date, created_at, id),
  KEY ix_cash_movements_account_id (cash_account_id, id),
  CONSTRAINT fk_cash_movements_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT,
  CONSTRAINT fk_cash_movements_account FOREIGN KEY (cash_account_id) REFERENCES cash_accounts (id) ON DELETE RESTRICT,
  CONSTRAINT fk_cash_movements_operation_request FOREIGN KEY (operation_request_id) REFERENCES operation_requests (id) ON DELETE RESTRICT,
  CONSTRAINT fk_cash_movements_user FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT chk_cash_movements_type CHECK (movement_type IN ('INITIAL', 'SALE', 'CANCELLATION', 'PRIZE_PAYMENT', 'ENTRY', 'WITHDRAWAL', 'EXPENSE', 'ADJUSTMENT')),
  CONSTRAINT chk_cash_movements_direction CHECK (direction IN ('CREDIT', 'DEBIT')),
  CONSTRAINT chk_cash_movements_amount CHECK (amount > 0),
  CONSTRAINT chk_cash_movements_reason CHECK (
    movement_type NOT IN ('ENTRY', 'WITHDRAWAL', 'EXPENSE', 'ADJUSTMENT')
    OR (reason IS NOT NULL AND CHAR_LENGTH(TRIM(reason)) BETWEEN 1 AND 500)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
